on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-dev-cli-apps:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Login azd
        run: azd auth login --client-id ${{ secrets.AZURE_CLIENT_ID }} --tenant-id ${{ secrets.AZURE_TENANT_ID }} --client-secret ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Azure Dev Provision
        run: azd provision --no-prompt --debug
        env:
          AZURE_ENV_NAME: ${{ secrets.AZURE_ENV_NAME }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          mariaDBPassword: ${{ secrets.AZURE_MARIADB_PASSWORD}}
          fqdn: ${{ secrets.AZURE_FQDN}}
          applicationName: ${{ secrets.AZURE_APPLICATION_NAME}}
          adminUsername: ${{ secrets.AZURE_ADMIN_USERNAME}}
          adminPassword: ${{ secrets.AZURE_ADMIN_PASSWORD}}
